//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{


    public partial class apply_now
    {

        /// <summary>
        /// applyError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl applyError;

        /// <summary>
<<<<<<< HEAD:register.aspx.designer.cs
        /// ValidationSummary1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;

        /// <summary>
        /// regFullName control.
=======
        /// applySuccess control.
>>>>>>> d482849 (CRUD Operation in Gallery Page):User_Side/apply-now.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl applySuccess;

        /// <summary>
<<<<<<< HEAD:register.aspx.designer.cs
        /// rfvFullName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        /// <summary>
        /// regEmail control.
=======
        /// applyName control.
>>>>>>> d482849 (CRUD Operation in Gallery Page):User_Side/apply-now.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox applyName;

        /// <summary>
<<<<<<< HEAD:register.aspx.designer.cs
        /// rfvEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// revEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>
        /// regPhone control.
=======
        /// applyEmail control.
>>>>>>> d482849 (CRUD Operation in Gallery Page):User_Side/apply-now.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox applyEmail;

        /// <summary>
<<<<<<< HEAD:register.aspx.designer.cs
<<<<<<< HEAD
        /// revphone control.
=======
        /// RangeValidator1 control.
>>>>>>> a07d7b43e5df3d2a39d471b5037f413d3b0d14ab
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revphone;
=======
        protected global::System.Web.UI.WebControls.RangeValidator RangeValidator1;
>>>>>>> a07d7b43e5df3d2a39d471b5037f413d3b0d14ab

        /// <summary>
        /// regCourse control.
=======
        /// applyPhone control.
>>>>>>> d482849 (CRUD Operation in Gallery Page):User_Side/apply-now.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox applyPhone;

        /// <summary>
        /// applyProgram control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList applyProgram;

        /// <summary>
<<<<<<< HEAD:register.aspx.designer.cs
        /// password control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator password;

        /// <summary>
        /// regConfirmPassword control.
=======
        /// applyIntake control.
>>>>>>> d482849 (CRUD Operation in Gallery Page):User_Side/apply-now.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList applyIntake;

        /// <summary>
<<<<<<< HEAD:register.aspx.designer.cs
        /// confirmPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CompareValidator confirmPassword;

        /// <summary>
        /// regTerms control.
=======
        /// applyMessage control.
>>>>>>> d482849 (CRUD Operation in Gallery Page):User_Side/apply-now.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox applyMessage;

        /// <summary>
        /// applySubmitBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD:register.aspx.designer.cs
        protected global::System.Web.UI.WebControls.Button Button1;

        /// <summary>
        /// GridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView1;
=======
        protected global::System.Web.UI.WebControls.LinkButton applySubmitBtn;
>>>>>>> d482849 (CRUD Operation in Gallery Page):User_Side/apply-now.aspx.designer.cs
    }
}
