//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{


    public partial class register
    {

        /// <summary>
        /// registerError control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl registerError;

        /// <summary>
        /// regFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox regFullName;

        /// <summary>
        /// regEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox regEmail;

        /// <summary>
        /// regPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox regPhone;

        /// <summary>
        /// regCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList regCourse;

        /// <summary>
        /// regPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox regPassword;

        /// <summary>
        /// regConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox regConfirmPassword;

        /// <summary>
        /// regTerms control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox regTerms;

        /// <summary>
        /// Button1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton Button1;
    }
}
