//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{


    public partial class contact
    {

        /// <summary>
        /// contactName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox contactName;

        /// <summary>
        /// contactEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox contactEmail;

        /// <summary>
        /// contactSubject control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox contactSubject;

        /// <summary>
        /// contactMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox contactMessage;

        /// <summary>
        /// contactSendBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton contactSendBtn;
    }
}
