//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University
{


    public partial class login
    {

        /// <summary>
        /// loginIdentifier control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox loginIdentifier;

        /// <summary>
        /// loginPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox loginPassword;

        /// <summary>
        /// studentLoginBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton studentLoginBtn;
    }
}
